# Generated by Django 4.1.4 on 2023-01-10 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0004_playlist_alter_song_user_song_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='user_name',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
