# Generated by Django 4.1.4 on 2023-01-11 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_playlist_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='artist',
        ),
    ]
