# Generated by Django 4.1.4 on 2023-01-17 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_remove_song_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
            ],
        ),
    ]
